fix: require a filename for save as dialog
leaphy-robotics/leaphy-webbased-svelte pull request #57
Opened 2024-05-09 17:03 UTC by rmoesbergen

2024-05-09 18:47 UTC, sverben requested changes
you can add the required prop on the input element instead of checking in the save method,  this will in most browsers also trigger a tooltip indicating you haven't filled out the field, providing additional user feedback

2024-05-09 18:47 UTC, sverben commented on src/lib/components/core/popups/popups/Prompt.svelte
> +	requireValue: boolean;
this should probably be an optional parameter by adding a ? after it's name

2024-05-10 07:40 UTC, rmoesbergen commented
> you can add the required prop on the input element instead of checking in the save method, this will in most browsers also trigger a tooltip indicating you haven't filled out the field, providing additional user feedback

done, still need the return in save() to prevent the dialog from closing when the form is not valid

2024-05-10 10:31 UTC, koen1711 commented
Leaving review to @sverben

2024-05-11 13:52 UTC, sverben approved these changes

2024-05-11 13:57 UTC, merged